### The purpose of this script is to identify low-quality cells and doublets in individual datasets ###

library(celda)
library(SingleCellExperiment)
library(singleCellTK)
library(Seurat)
library(ggplot2)
library(scater)
library(patchwork)
library(dplyr)
library(kableExtra)

# -----------------------Cell type markers used--------------------------------------------------------
markers <- list(Tcell_Markers = c("Trbc2", "Cd3g", "Trac"),
                 Bcell_Markers = c("Cd79a", "Cd79b", "Igkc"),
                 NKcell_Markers = c("Gzma", "Nkg7", "Ncr1"),
                 Macro_Markers = c("C1qa", "Cd209a", "Adgre1"),
                 Acinar_Markers = c("Prom2", "Aqp5", "Bhlha15", "Lpo"),
                 Ductal_Markers = c("Wfdc2", "Krt14", "Krt7"),
                 Myo_Markers = c("Acta2", "Myh11", "Krt14"),
                 Fibro_Markers = c("Col1a1", "Apod", "Dcn"))

#-----------------------Run DecontX with z argument on individual datasets------------------------------

# For each of the samples, open the filtered_feature_bc_matrix generated by CellRanger using Read10X(): Female=9737 cells; Male_1=6422 cells; Male_2=6899 cells
# then, create seurat object and cluster the cells
filtered <- CreateSeuratObject(counts = filtered, project = "Young LG", min.cells = 3, min.features = 0)
seurat_SCT <- SCTransform(filtered, assay="RNA", new.assay.name = "SCT", return.only.var.genes = T, verbose = TRUE) %>%
  RunPCA(verbose = TRUE) %>% 
  FindNeighbors(dims = 1:50) %>% 
  RunUMAP(dims = 1:50)  
#not shown: identify main populations (Acinar cells, Ducts, MEC, T cells, Myeloid, NK cells, endothelium, fibroblasts) on the UMAP plot using marker genes to determine the right resolution
#res= 0.05 for Female LG (9 clusters), 0.1 for Male 1 (9 clusters) and 0.06 for Male 2 (8 clusters)
seurat_SCT <- FindClusters(seurat_SCT, resolution=res)

#create the vector of cluster identities that will be supplied to the z argument
clusters <- seurat_SCT$seurat_clusters

# convert to sce object, run doublet identification packages and decontX
filtered <- as.SingleCellExperiment(filtered)
filtered <- runCellQC(filtered, algorithms = c("scDblFinder", "cxds", "bcds", "cxds_bcds_hybrid", "doubletFinder"))
filtered <- decontX(filtered, assayName="counts", z=clusters, verbose=TRUE)
saveRDS(filtered, file="filtered matrix_QCnoBG_zarg.rds")

# not shown: 
    # (1) generate QC results report and check the correction of gene expression
    # (2) investigate seurat_SCT with high resolution clustering to visualize QC scores and determine appropriate QC thresholds

# Create the list of highly contaminated barcodes
conta <- subset(seurat_SCT, decontX_contamination>=0.7) %>% colnames()

# make the list of true doublets (both scores>0.25)
trueDoublets <- subset(clean, scDblFinder_score>=0.25)
trueDoublets <- subset(trueDoublets, DoubletFinder_score>=0.25) %>% colnames()

# create the list of cells to exclude from the analysis based on QC scores
elim <- c(conta, trueDoublets)
# remove all low-quality cells and save the list of barcodes retained for data integration
seurat_SCT <- subset(seurat_SCT, cells=elim.cells, invert=TRUE) # Remaining cell numbers at this step: Female=8250 cells; Male_1=5138 cells; Male_2=4799 cells
good.cells <- subset(seurat_SCT, subset= nFeature_RNA>200 & percent.mt<15 & nCount_RNA>500) %>% colnames() # Remaining cell numbers at this step: Female=7056 cells; Male_1=4723 cells; Male_2=4493 cells
write.csv(good.cells, "Cells to keep.csv") 

# Note: no additional low-quality cluster was identified by performing high resolution clustering of (1) individual datasets and (2) following the integration of the 3 samples using decontX-counts and the list of 'good.cells'
